name: Sort imports
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sort_imports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: isort/isort-action@v1